title: Sep Driessen
author: Sep Driessen
email: josephus.driessen_AT_iit.it
description: > # this means to ignore newlines until "twitter_username:"
  Personal website of Josephus (Sep) J. M. Driessen

baseurl: #"/sepdriessen"
url: "http://sepdriessen.github.io/"


# social links
# twitter_username: jekyllrb
# github_username:  jekyll
# rss: rss
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
linkedin_username: sep-driessen-90193972
# pinterest_username: jekyll
# youtube_username: MrSeppieD
# googleplus_username: +jekyll

# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com

# Default frontmatters (not working?)
# defaults:
#   -
#     scope:
#       path: ""
#       type: ""
#     values:
#       author: Sep Driessen


show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - pages/research.md
 - pages/publications.md


# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
